// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pacman.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pacman_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pacman_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pacman_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pacman_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pacman_2eproto;
namespace pacman {
class GameState;
struct GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class GhostState;
struct GhostStateDefaultTypeInternal;
extern GhostStateDefaultTypeInternal _GhostState_default_instance_;
class KeyInput;
struct KeyInputDefaultTypeInternal;
extern KeyInputDefaultTypeInternal _KeyInput_default_instance_;
}  // namespace pacman
PROTOBUF_NAMESPACE_OPEN
template<> ::pacman::GameState* Arena::CreateMaybeMessage<::pacman::GameState>(Arena*);
template<> ::pacman::GhostState* Arena::CreateMaybeMessage<::pacman::GhostState>(Arena*);
template<> ::pacman::KeyInput* Arena::CreateMaybeMessage<::pacman::KeyInput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pacman {

enum KeyAction : int {
  KEY_NONE = 0,
  KEY_UP = 1,
  KEY_DOWN = 2,
  KEY_LEFT = 3,
  KEY_RIGHT = 4,
  KeyAction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  KeyAction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool KeyAction_IsValid(int value);
constexpr KeyAction KeyAction_MIN = KEY_NONE;
constexpr KeyAction KeyAction_MAX = KEY_RIGHT;
constexpr int KeyAction_ARRAYSIZE = KeyAction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyAction_descriptor();
template<typename T>
inline const std::string& KeyAction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, KeyAction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function KeyAction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    KeyAction_descriptor(), enum_t_value);
}
inline bool KeyAction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, KeyAction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<KeyAction>(
    KeyAction_descriptor(), name, value);
}
// ===================================================================

class GhostState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pacman.GhostState) */ {
 public:
  inline GhostState() : GhostState(nullptr) {}
  ~GhostState() override;
  explicit PROTOBUF_CONSTEXPR GhostState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GhostState(const GhostState& from);
  GhostState(GhostState&& from) noexcept
    : GhostState() {
    *this = ::std::move(from);
  }

  inline GhostState& operator=(const GhostState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GhostState& operator=(GhostState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GhostState& default_instance() {
    return *internal_default_instance();
  }
  static inline const GhostState* internal_default_instance() {
    return reinterpret_cast<const GhostState*>(
               &_GhostState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GhostState& a, GhostState& b) {
    a.Swap(&b);
  }
  inline void Swap(GhostState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GhostState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GhostState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GhostState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GhostState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GhostState& from) {
    GhostState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GhostState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pacman.GhostState";
  }
  protected:
  explicit GhostState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kAngleFieldNumber = 3,
    kEdibleFieldNumber = 4,
    kEatenFieldNumber = 5,
    kColorRFieldNumber = 6,
    kColorGFieldNumber = 7,
    kColorBFieldNumber = 8,
    kEdibleTimerFieldNumber = 9,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double angle = 3;
  void clear_angle();
  double angle() const;
  void set_angle(double value);
  private:
  double _internal_angle() const;
  void _internal_set_angle(double value);
  public:

  // bool edible = 4;
  void clear_edible();
  bool edible() const;
  void set_edible(bool value);
  private:
  bool _internal_edible() const;
  void _internal_set_edible(bool value);
  public:

  // bool eaten = 5;
  void clear_eaten();
  bool eaten() const;
  void set_eaten(bool value);
  private:
  bool _internal_eaten() const;
  void _internal_set_eaten(bool value);
  public:

  // float color_r = 6;
  void clear_color_r();
  float color_r() const;
  void set_color_r(float value);
  private:
  float _internal_color_r() const;
  void _internal_set_color_r(float value);
  public:

  // float color_g = 7;
  void clear_color_g();
  float color_g() const;
  void set_color_g(float value);
  private:
  float _internal_color_g() const;
  void _internal_set_color_g(float value);
  public:

  // float color_b = 8;
  void clear_color_b();
  float color_b() const;
  void set_color_b(float value);
  private:
  float _internal_color_b() const;
  void _internal_set_color_b(float value);
  public:

  // int32 edible_timer = 9;
  void clear_edible_timer();
  int32_t edible_timer() const;
  void set_edible_timer(int32_t value);
  private:
  int32_t _internal_edible_timer() const;
  void _internal_set_edible_timer(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pacman.GhostState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double angle_;
    bool edible_;
    bool eaten_;
    float color_r_;
    float color_g_;
    float color_b_;
    int32_t edible_timer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pacman_2eproto;
};
// -------------------------------------------------------------------

class GameState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pacman.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  ~GameState() override;
  explicit PROTOBUF_CONSTEXPR GameState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameState(const GameState& from);
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameState& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }
  inline void Swap(GameState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameState& from) {
    GameState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pacman.GameState";
  }
  protected:
  explicit GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGhostsFieldNumber = 10,
    kPebbleArrayFieldNumber = 11,
    kPacXFieldNumber = 1,
    kPacYFieldNumber = 2,
    kPacAngleFieldNumber = 3,
    kLivesFieldNumber = 5,
    kPointsFieldNumber = 6,
    kAnimateFieldNumber = 4,
    kGameoverFieldNumber = 7,
    kStartWaitFieldNumber = 8,
    kPebblesLeftFieldNumber = 9,
  };
  // repeated .pacman.GhostState ghosts = 10;
  int ghosts_size() const;
  private:
  int _internal_ghosts_size() const;
  public:
  void clear_ghosts();
  ::pacman::GhostState* mutable_ghosts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pacman::GhostState >*
      mutable_ghosts();
  private:
  const ::pacman::GhostState& _internal_ghosts(int index) const;
  ::pacman::GhostState* _internal_add_ghosts();
  public:
  const ::pacman::GhostState& ghosts(int index) const;
  ::pacman::GhostState* add_ghosts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pacman::GhostState >&
      ghosts() const;

  // repeated int32 pebble_array = 11;
  int pebble_array_size() const;
  private:
  int _internal_pebble_array_size() const;
  public:
  void clear_pebble_array();
  private:
  int32_t _internal_pebble_array(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_pebble_array() const;
  void _internal_add_pebble_array(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_pebble_array();
  public:
  int32_t pebble_array(int index) const;
  void set_pebble_array(int index, int32_t value);
  void add_pebble_array(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      pebble_array() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_pebble_array();

  // double pac_x = 1;
  void clear_pac_x();
  double pac_x() const;
  void set_pac_x(double value);
  private:
  double _internal_pac_x() const;
  void _internal_set_pac_x(double value);
  public:

  // double pac_y = 2;
  void clear_pac_y();
  double pac_y() const;
  void set_pac_y(double value);
  private:
  double _internal_pac_y() const;
  void _internal_set_pac_y(double value);
  public:

  // double pac_angle = 3;
  void clear_pac_angle();
  double pac_angle() const;
  void set_pac_angle(double value);
  private:
  double _internal_pac_angle() const;
  void _internal_set_pac_angle(double value);
  public:

  // int32 lives = 5;
  void clear_lives();
  int32_t lives() const;
  void set_lives(int32_t value);
  private:
  int32_t _internal_lives() const;
  void _internal_set_lives(int32_t value);
  public:

  // int32 points = 6;
  void clear_points();
  int32_t points() const;
  void set_points(int32_t value);
  private:
  int32_t _internal_points() const;
  void _internal_set_points(int32_t value);
  public:

  // bool animate = 4;
  void clear_animate();
  bool animate() const;
  void set_animate(bool value);
  private:
  bool _internal_animate() const;
  void _internal_set_animate(bool value);
  public:

  // bool gameover = 7;
  void clear_gameover();
  bool gameover() const;
  void set_gameover(bool value);
  private:
  bool _internal_gameover() const;
  void _internal_set_gameover(bool value);
  public:

  // bool start_wait = 8;
  void clear_start_wait();
  bool start_wait() const;
  void set_start_wait(bool value);
  private:
  bool _internal_start_wait() const;
  void _internal_set_start_wait(bool value);
  public:

  // int32 pebbles_left = 9;
  void clear_pebbles_left();
  int32_t pebbles_left() const;
  void set_pebbles_left(int32_t value);
  private:
  int32_t _internal_pebbles_left() const;
  void _internal_set_pebbles_left(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pacman.GameState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pacman::GhostState > ghosts_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > pebble_array_;
    mutable std::atomic<int> _pebble_array_cached_byte_size_;
    double pac_x_;
    double pac_y_;
    double pac_angle_;
    int32_t lives_;
    int32_t points_;
    bool animate_;
    bool gameover_;
    bool start_wait_;
    int32_t pebbles_left_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pacman_2eproto;
};
// -------------------------------------------------------------------

class KeyInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pacman.KeyInput) */ {
 public:
  inline KeyInput() : KeyInput(nullptr) {}
  ~KeyInput() override;
  explicit PROTOBUF_CONSTEXPR KeyInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KeyInput(const KeyInput& from);
  KeyInput(KeyInput&& from) noexcept
    : KeyInput() {
    *this = ::std::move(from);
  }

  inline KeyInput& operator=(const KeyInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyInput& operator=(KeyInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const KeyInput* internal_default_instance() {
    return reinterpret_cast<const KeyInput*>(
               &_KeyInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(KeyInput& a, KeyInput& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KeyInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KeyInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const KeyInput& from) {
    KeyInput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pacman.KeyInput";
  }
  protected:
  explicit KeyInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionFieldNumber = 1,
    kPressedFieldNumber = 2,
  };
  // .pacman.KeyAction action = 1;
  void clear_action();
  ::pacman::KeyAction action() const;
  void set_action(::pacman::KeyAction value);
  private:
  ::pacman::KeyAction _internal_action() const;
  void _internal_set_action(::pacman::KeyAction value);
  public:

  // bool pressed = 2;
  void clear_pressed();
  bool pressed() const;
  void set_pressed(bool value);
  private:
  bool _internal_pressed() const;
  void _internal_set_pressed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:pacman.KeyInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int action_;
    bool pressed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pacman_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GhostState

// double x = 1;
inline void GhostState::clear_x() {
  _impl_.x_ = 0;
}
inline double GhostState::_internal_x() const {
  return _impl_.x_;
}
inline double GhostState::x() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.x)
  return _internal_x();
}
inline void GhostState::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void GhostState::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.x)
}

// double y = 2;
inline void GhostState::clear_y() {
  _impl_.y_ = 0;
}
inline double GhostState::_internal_y() const {
  return _impl_.y_;
}
inline double GhostState::y() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.y)
  return _internal_y();
}
inline void GhostState::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void GhostState::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.y)
}

// double angle = 3;
inline void GhostState::clear_angle() {
  _impl_.angle_ = 0;
}
inline double GhostState::_internal_angle() const {
  return _impl_.angle_;
}
inline double GhostState::angle() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.angle)
  return _internal_angle();
}
inline void GhostState::_internal_set_angle(double value) {
  
  _impl_.angle_ = value;
}
inline void GhostState::set_angle(double value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.angle)
}

// bool edible = 4;
inline void GhostState::clear_edible() {
  _impl_.edible_ = false;
}
inline bool GhostState::_internal_edible() const {
  return _impl_.edible_;
}
inline bool GhostState::edible() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.edible)
  return _internal_edible();
}
inline void GhostState::_internal_set_edible(bool value) {
  
  _impl_.edible_ = value;
}
inline void GhostState::set_edible(bool value) {
  _internal_set_edible(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.edible)
}

// bool eaten = 5;
inline void GhostState::clear_eaten() {
  _impl_.eaten_ = false;
}
inline bool GhostState::_internal_eaten() const {
  return _impl_.eaten_;
}
inline bool GhostState::eaten() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.eaten)
  return _internal_eaten();
}
inline void GhostState::_internal_set_eaten(bool value) {
  
  _impl_.eaten_ = value;
}
inline void GhostState::set_eaten(bool value) {
  _internal_set_eaten(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.eaten)
}

// float color_r = 6;
inline void GhostState::clear_color_r() {
  _impl_.color_r_ = 0;
}
inline float GhostState::_internal_color_r() const {
  return _impl_.color_r_;
}
inline float GhostState::color_r() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.color_r)
  return _internal_color_r();
}
inline void GhostState::_internal_set_color_r(float value) {
  
  _impl_.color_r_ = value;
}
inline void GhostState::set_color_r(float value) {
  _internal_set_color_r(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.color_r)
}

// float color_g = 7;
inline void GhostState::clear_color_g() {
  _impl_.color_g_ = 0;
}
inline float GhostState::_internal_color_g() const {
  return _impl_.color_g_;
}
inline float GhostState::color_g() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.color_g)
  return _internal_color_g();
}
inline void GhostState::_internal_set_color_g(float value) {
  
  _impl_.color_g_ = value;
}
inline void GhostState::set_color_g(float value) {
  _internal_set_color_g(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.color_g)
}

// float color_b = 8;
inline void GhostState::clear_color_b() {
  _impl_.color_b_ = 0;
}
inline float GhostState::_internal_color_b() const {
  return _impl_.color_b_;
}
inline float GhostState::color_b() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.color_b)
  return _internal_color_b();
}
inline void GhostState::_internal_set_color_b(float value) {
  
  _impl_.color_b_ = value;
}
inline void GhostState::set_color_b(float value) {
  _internal_set_color_b(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.color_b)
}

// int32 edible_timer = 9;
inline void GhostState::clear_edible_timer() {
  _impl_.edible_timer_ = 0;
}
inline int32_t GhostState::_internal_edible_timer() const {
  return _impl_.edible_timer_;
}
inline int32_t GhostState::edible_timer() const {
  // @@protoc_insertion_point(field_get:pacman.GhostState.edible_timer)
  return _internal_edible_timer();
}
inline void GhostState::_internal_set_edible_timer(int32_t value) {
  
  _impl_.edible_timer_ = value;
}
inline void GhostState::set_edible_timer(int32_t value) {
  _internal_set_edible_timer(value);
  // @@protoc_insertion_point(field_set:pacman.GhostState.edible_timer)
}

// -------------------------------------------------------------------

// GameState

// double pac_x = 1;
inline void GameState::clear_pac_x() {
  _impl_.pac_x_ = 0;
}
inline double GameState::_internal_pac_x() const {
  return _impl_.pac_x_;
}
inline double GameState::pac_x() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.pac_x)
  return _internal_pac_x();
}
inline void GameState::_internal_set_pac_x(double value) {
  
  _impl_.pac_x_ = value;
}
inline void GameState::set_pac_x(double value) {
  _internal_set_pac_x(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.pac_x)
}

// double pac_y = 2;
inline void GameState::clear_pac_y() {
  _impl_.pac_y_ = 0;
}
inline double GameState::_internal_pac_y() const {
  return _impl_.pac_y_;
}
inline double GameState::pac_y() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.pac_y)
  return _internal_pac_y();
}
inline void GameState::_internal_set_pac_y(double value) {
  
  _impl_.pac_y_ = value;
}
inline void GameState::set_pac_y(double value) {
  _internal_set_pac_y(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.pac_y)
}

// double pac_angle = 3;
inline void GameState::clear_pac_angle() {
  _impl_.pac_angle_ = 0;
}
inline double GameState::_internal_pac_angle() const {
  return _impl_.pac_angle_;
}
inline double GameState::pac_angle() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.pac_angle)
  return _internal_pac_angle();
}
inline void GameState::_internal_set_pac_angle(double value) {
  
  _impl_.pac_angle_ = value;
}
inline void GameState::set_pac_angle(double value) {
  _internal_set_pac_angle(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.pac_angle)
}

// bool animate = 4;
inline void GameState::clear_animate() {
  _impl_.animate_ = false;
}
inline bool GameState::_internal_animate() const {
  return _impl_.animate_;
}
inline bool GameState::animate() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.animate)
  return _internal_animate();
}
inline void GameState::_internal_set_animate(bool value) {
  
  _impl_.animate_ = value;
}
inline void GameState::set_animate(bool value) {
  _internal_set_animate(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.animate)
}

// int32 lives = 5;
inline void GameState::clear_lives() {
  _impl_.lives_ = 0;
}
inline int32_t GameState::_internal_lives() const {
  return _impl_.lives_;
}
inline int32_t GameState::lives() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.lives)
  return _internal_lives();
}
inline void GameState::_internal_set_lives(int32_t value) {
  
  _impl_.lives_ = value;
}
inline void GameState::set_lives(int32_t value) {
  _internal_set_lives(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.lives)
}

// int32 points = 6;
inline void GameState::clear_points() {
  _impl_.points_ = 0;
}
inline int32_t GameState::_internal_points() const {
  return _impl_.points_;
}
inline int32_t GameState::points() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.points)
  return _internal_points();
}
inline void GameState::_internal_set_points(int32_t value) {
  
  _impl_.points_ = value;
}
inline void GameState::set_points(int32_t value) {
  _internal_set_points(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.points)
}

// bool gameover = 7;
inline void GameState::clear_gameover() {
  _impl_.gameover_ = false;
}
inline bool GameState::_internal_gameover() const {
  return _impl_.gameover_;
}
inline bool GameState::gameover() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.gameover)
  return _internal_gameover();
}
inline void GameState::_internal_set_gameover(bool value) {
  
  _impl_.gameover_ = value;
}
inline void GameState::set_gameover(bool value) {
  _internal_set_gameover(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.gameover)
}

// bool start_wait = 8;
inline void GameState::clear_start_wait() {
  _impl_.start_wait_ = false;
}
inline bool GameState::_internal_start_wait() const {
  return _impl_.start_wait_;
}
inline bool GameState::start_wait() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.start_wait)
  return _internal_start_wait();
}
inline void GameState::_internal_set_start_wait(bool value) {
  
  _impl_.start_wait_ = value;
}
inline void GameState::set_start_wait(bool value) {
  _internal_set_start_wait(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.start_wait)
}

// int32 pebbles_left = 9;
inline void GameState::clear_pebbles_left() {
  _impl_.pebbles_left_ = 0;
}
inline int32_t GameState::_internal_pebbles_left() const {
  return _impl_.pebbles_left_;
}
inline int32_t GameState::pebbles_left() const {
  // @@protoc_insertion_point(field_get:pacman.GameState.pebbles_left)
  return _internal_pebbles_left();
}
inline void GameState::_internal_set_pebbles_left(int32_t value) {
  
  _impl_.pebbles_left_ = value;
}
inline void GameState::set_pebbles_left(int32_t value) {
  _internal_set_pebbles_left(value);
  // @@protoc_insertion_point(field_set:pacman.GameState.pebbles_left)
}

// repeated .pacman.GhostState ghosts = 10;
inline int GameState::_internal_ghosts_size() const {
  return _impl_.ghosts_.size();
}
inline int GameState::ghosts_size() const {
  return _internal_ghosts_size();
}
inline void GameState::clear_ghosts() {
  _impl_.ghosts_.Clear();
}
inline ::pacman::GhostState* GameState::mutable_ghosts(int index) {
  // @@protoc_insertion_point(field_mutable:pacman.GameState.ghosts)
  return _impl_.ghosts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pacman::GhostState >*
GameState::mutable_ghosts() {
  // @@protoc_insertion_point(field_mutable_list:pacman.GameState.ghosts)
  return &_impl_.ghosts_;
}
inline const ::pacman::GhostState& GameState::_internal_ghosts(int index) const {
  return _impl_.ghosts_.Get(index);
}
inline const ::pacman::GhostState& GameState::ghosts(int index) const {
  // @@protoc_insertion_point(field_get:pacman.GameState.ghosts)
  return _internal_ghosts(index);
}
inline ::pacman::GhostState* GameState::_internal_add_ghosts() {
  return _impl_.ghosts_.Add();
}
inline ::pacman::GhostState* GameState::add_ghosts() {
  ::pacman::GhostState* _add = _internal_add_ghosts();
  // @@protoc_insertion_point(field_add:pacman.GameState.ghosts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pacman::GhostState >&
GameState::ghosts() const {
  // @@protoc_insertion_point(field_list:pacman.GameState.ghosts)
  return _impl_.ghosts_;
}

// repeated int32 pebble_array = 11;
inline int GameState::_internal_pebble_array_size() const {
  return _impl_.pebble_array_.size();
}
inline int GameState::pebble_array_size() const {
  return _internal_pebble_array_size();
}
inline void GameState::clear_pebble_array() {
  _impl_.pebble_array_.Clear();
}
inline int32_t GameState::_internal_pebble_array(int index) const {
  return _impl_.pebble_array_.Get(index);
}
inline int32_t GameState::pebble_array(int index) const {
  // @@protoc_insertion_point(field_get:pacman.GameState.pebble_array)
  return _internal_pebble_array(index);
}
inline void GameState::set_pebble_array(int index, int32_t value) {
  _impl_.pebble_array_.Set(index, value);
  // @@protoc_insertion_point(field_set:pacman.GameState.pebble_array)
}
inline void GameState::_internal_add_pebble_array(int32_t value) {
  _impl_.pebble_array_.Add(value);
}
inline void GameState::add_pebble_array(int32_t value) {
  _internal_add_pebble_array(value);
  // @@protoc_insertion_point(field_add:pacman.GameState.pebble_array)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GameState::_internal_pebble_array() const {
  return _impl_.pebble_array_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GameState::pebble_array() const {
  // @@protoc_insertion_point(field_list:pacman.GameState.pebble_array)
  return _internal_pebble_array();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GameState::_internal_mutable_pebble_array() {
  return &_impl_.pebble_array_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GameState::mutable_pebble_array() {
  // @@protoc_insertion_point(field_mutable_list:pacman.GameState.pebble_array)
  return _internal_mutable_pebble_array();
}

// -------------------------------------------------------------------

// KeyInput

// .pacman.KeyAction action = 1;
inline void KeyInput::clear_action() {
  _impl_.action_ = 0;
}
inline ::pacman::KeyAction KeyInput::_internal_action() const {
  return static_cast< ::pacman::KeyAction >(_impl_.action_);
}
inline ::pacman::KeyAction KeyInput::action() const {
  // @@protoc_insertion_point(field_get:pacman.KeyInput.action)
  return _internal_action();
}
inline void KeyInput::_internal_set_action(::pacman::KeyAction value) {
  
  _impl_.action_ = value;
}
inline void KeyInput::set_action(::pacman::KeyAction value) {
  _internal_set_action(value);
  // @@protoc_insertion_point(field_set:pacman.KeyInput.action)
}

// bool pressed = 2;
inline void KeyInput::clear_pressed() {
  _impl_.pressed_ = false;
}
inline bool KeyInput::_internal_pressed() const {
  return _impl_.pressed_;
}
inline bool KeyInput::pressed() const {
  // @@protoc_insertion_point(field_get:pacman.KeyInput.pressed)
  return _internal_pressed();
}
inline void KeyInput::_internal_set_pressed(bool value) {
  
  _impl_.pressed_ = value;
}
inline void KeyInput::set_pressed(bool value) {
  _internal_set_pressed(value);
  // @@protoc_insertion_point(field_set:pacman.KeyInput.pressed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pacman

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::pacman::KeyAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pacman::KeyAction>() {
  return ::pacman::KeyAction_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pacman_2eproto
