// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pacman.proto

#include "pacman.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pacman {
PROTOBUF_CONSTEXPR GhostState::GhostState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.angle_)*/0
  , /*decltype(_impl_.edible_)*/false
  , /*decltype(_impl_.eaten_)*/false
  , /*decltype(_impl_.color_r_)*/0
  , /*decltype(_impl_.color_g_)*/0
  , /*decltype(_impl_.color_b_)*/0
  , /*decltype(_impl_.edible_timer_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GhostStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GhostStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GhostStateDefaultTypeInternal() {}
  union {
    GhostState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GhostStateDefaultTypeInternal _GhostState_default_instance_;
PROTOBUF_CONSTEXPR GameState::GameState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ghosts_)*/{}
  , /*decltype(_impl_.pebble_array_)*/{}
  , /*decltype(_impl_._pebble_array_cached_byte_size_)*/{0}
  , /*decltype(_impl_.pac_x_)*/0
  , /*decltype(_impl_.pac_y_)*/0
  , /*decltype(_impl_.pac_angle_)*/0
  , /*decltype(_impl_.lives_)*/0
  , /*decltype(_impl_.points_)*/0
  , /*decltype(_impl_.animate_)*/false
  , /*decltype(_impl_.gameover_)*/false
  , /*decltype(_impl_.start_wait_)*/false
  , /*decltype(_impl_.pebbles_left_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameStateDefaultTypeInternal() {}
  union {
    GameState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameStateDefaultTypeInternal _GameState_default_instance_;
PROTOBUF_CONSTEXPR KeyInput::KeyInput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.action_)*/0
  , /*decltype(_impl_.pressed_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KeyInputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyInputDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyInputDefaultTypeInternal() {}
  union {
    KeyInput _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyInputDefaultTypeInternal _KeyInput_default_instance_;
}  // namespace pacman
static ::_pb::Metadata file_level_metadata_pacman_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_pacman_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pacman_2eproto = nullptr;

const uint32_t TableStruct_pacman_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.angle_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.edible_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.eaten_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.color_r_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.color_g_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.color_b_),
  PROTOBUF_FIELD_OFFSET(::pacman::GhostState, _impl_.edible_timer_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.pac_x_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.pac_y_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.pac_angle_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.animate_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.lives_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.points_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.gameover_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.start_wait_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.pebbles_left_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.ghosts_),
  PROTOBUF_FIELD_OFFSET(::pacman::GameState, _impl_.pebble_array_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pacman::KeyInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pacman::KeyInput, _impl_.action_),
  PROTOBUF_FIELD_OFFSET(::pacman::KeyInput, _impl_.pressed_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pacman::GhostState)},
  { 15, -1, -1, sizeof(::pacman::GameState)},
  { 32, -1, -1, sizeof(::pacman::KeyInput)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pacman::_GhostState_default_instance_._instance,
  &::pacman::_GameState_default_instance_._instance,
  &::pacman::_KeyInput_default_instance_._instance,
};

const char descriptor_table_protodef_pacman_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014pacman.proto\022\006pacman\"\231\001\n\nGhostState\022\t\n"
  "\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\r\n\005angle\030\003 \001(\001\022\016\n\006ed"
  "ible\030\004 \001(\010\022\r\n\005eaten\030\005 \001(\010\022\017\n\007color_r\030\006 \001"
  "(\002\022\017\n\007color_g\030\007 \001(\002\022\017\n\007color_b\030\010 \001(\002\022\024\n\014"
  "edible_timer\030\t \001(\005\"\342\001\n\tGameState\022\r\n\005pac_"
  "x\030\001 \001(\001\022\r\n\005pac_y\030\002 \001(\001\022\021\n\tpac_angle\030\003 \001("
  "\001\022\017\n\007animate\030\004 \001(\010\022\r\n\005lives\030\005 \001(\005\022\016\n\006poi"
  "nts\030\006 \001(\005\022\020\n\010gameover\030\007 \001(\010\022\022\n\nstart_wai"
  "t\030\010 \001(\010\022\024\n\014pebbles_left\030\t \001(\005\022\"\n\006ghosts\030"
  "\n \003(\0132\022.pacman.GhostState\022\024\n\014pebble_arra"
  "y\030\013 \003(\005\">\n\010KeyInput\022!\n\006action\030\001 \001(\0162\021.pa"
  "cman.KeyAction\022\017\n\007pressed\030\002 \001(\010*P\n\tKeyAc"
  "tion\022\014\n\010KEY_NONE\020\000\022\n\n\006KEY_UP\020\001\022\014\n\010KEY_DO"
  "WN\020\002\022\014\n\010KEY_LEFT\020\003\022\r\n\tKEY_RIGHT\020\004b\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_pacman_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pacman_2eproto = {
    false, false, 561, descriptor_table_protodef_pacman_2eproto,
    "pacman.proto",
    &descriptor_table_pacman_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_pacman_2eproto::offsets,
    file_level_metadata_pacman_2eproto, file_level_enum_descriptors_pacman_2eproto,
    file_level_service_descriptors_pacman_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pacman_2eproto_getter() {
  return &descriptor_table_pacman_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pacman_2eproto(&descriptor_table_pacman_2eproto);
namespace pacman {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_pacman_2eproto);
  return file_level_enum_descriptors_pacman_2eproto[0];
}
bool KeyAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class GhostState::_Internal {
 public:
};

GhostState::GhostState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pacman.GhostState)
}
GhostState::GhostState(const GhostState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GhostState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.angle_){}
    , decltype(_impl_.edible_){}
    , decltype(_impl_.eaten_){}
    , decltype(_impl_.color_r_){}
    , decltype(_impl_.color_g_){}
    , decltype(_impl_.color_b_){}
    , decltype(_impl_.edible_timer_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.edible_timer_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.edible_timer_));
  // @@protoc_insertion_point(copy_constructor:pacman.GhostState)
}

inline void GhostState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.angle_){0}
    , decltype(_impl_.edible_){false}
    , decltype(_impl_.eaten_){false}
    , decltype(_impl_.color_r_){0}
    , decltype(_impl_.color_g_){0}
    , decltype(_impl_.color_b_){0}
    , decltype(_impl_.edible_timer_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GhostState::~GhostState() {
  // @@protoc_insertion_point(destructor:pacman.GhostState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GhostState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GhostState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GhostState::Clear() {
// @@protoc_insertion_point(message_clear_start:pacman.GhostState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.edible_timer_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.edible_timer_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GhostState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double angle = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.angle_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool edible = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.edible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool eaten = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.eaten_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float color_r = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.color_r_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float color_g = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.color_g_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float color_b = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.color_b_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 edible_timer = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.edible_timer_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GhostState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pacman.GhostState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // double angle = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = this->_internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_angle(), target);
  }

  // bool edible = 4;
  if (this->_internal_edible() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_edible(), target);
  }

  // bool eaten = 5;
  if (this->_internal_eaten() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_eaten(), target);
  }

  // float color_r = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_r = this->_internal_color_r();
  uint32_t raw_color_r;
  memcpy(&raw_color_r, &tmp_color_r, sizeof(tmp_color_r));
  if (raw_color_r != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_color_r(), target);
  }

  // float color_g = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_g = this->_internal_color_g();
  uint32_t raw_color_g;
  memcpy(&raw_color_g, &tmp_color_g, sizeof(tmp_color_g));
  if (raw_color_g != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_color_g(), target);
  }

  // float color_b = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_b = this->_internal_color_b();
  uint32_t raw_color_b;
  memcpy(&raw_color_b, &tmp_color_b, sizeof(tmp_color_b));
  if (raw_color_b != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_color_b(), target);
  }

  // int32 edible_timer = 9;
  if (this->_internal_edible_timer() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_edible_timer(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pacman.GhostState)
  return target;
}

size_t GhostState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pacman.GhostState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 8;
  }

  // double angle = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = this->_internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    total_size += 1 + 8;
  }

  // bool edible = 4;
  if (this->_internal_edible() != 0) {
    total_size += 1 + 1;
  }

  // bool eaten = 5;
  if (this->_internal_eaten() != 0) {
    total_size += 1 + 1;
  }

  // float color_r = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_r = this->_internal_color_r();
  uint32_t raw_color_r;
  memcpy(&raw_color_r, &tmp_color_r, sizeof(tmp_color_r));
  if (raw_color_r != 0) {
    total_size += 1 + 4;
  }

  // float color_g = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_g = this->_internal_color_g();
  uint32_t raw_color_g;
  memcpy(&raw_color_g, &tmp_color_g, sizeof(tmp_color_g));
  if (raw_color_g != 0) {
    total_size += 1 + 4;
  }

  // float color_b = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_b = this->_internal_color_b();
  uint32_t raw_color_b;
  memcpy(&raw_color_b, &tmp_color_b, sizeof(tmp_color_b));
  if (raw_color_b != 0) {
    total_size += 1 + 4;
  }

  // int32 edible_timer = 9;
  if (this->_internal_edible_timer() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_edible_timer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GhostState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GhostState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GhostState::GetClassData() const { return &_class_data_; }


void GhostState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GhostState*>(&to_msg);
  auto& from = static_cast<const GhostState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pacman.GhostState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = from._internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    _this->_internal_set_angle(from._internal_angle());
  }
  if (from._internal_edible() != 0) {
    _this->_internal_set_edible(from._internal_edible());
  }
  if (from._internal_eaten() != 0) {
    _this->_internal_set_eaten(from._internal_eaten());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_r = from._internal_color_r();
  uint32_t raw_color_r;
  memcpy(&raw_color_r, &tmp_color_r, sizeof(tmp_color_r));
  if (raw_color_r != 0) {
    _this->_internal_set_color_r(from._internal_color_r());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_g = from._internal_color_g();
  uint32_t raw_color_g;
  memcpy(&raw_color_g, &tmp_color_g, sizeof(tmp_color_g));
  if (raw_color_g != 0) {
    _this->_internal_set_color_g(from._internal_color_g());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_color_b = from._internal_color_b();
  uint32_t raw_color_b;
  memcpy(&raw_color_b, &tmp_color_b, sizeof(tmp_color_b));
  if (raw_color_b != 0) {
    _this->_internal_set_color_b(from._internal_color_b());
  }
  if (from._internal_edible_timer() != 0) {
    _this->_internal_set_edible_timer(from._internal_edible_timer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GhostState::CopyFrom(const GhostState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pacman.GhostState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GhostState::IsInitialized() const {
  return true;
}

void GhostState::InternalSwap(GhostState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GhostState, _impl_.edible_timer_)
      + sizeof(GhostState::_impl_.edible_timer_)
      - PROTOBUF_FIELD_OFFSET(GhostState, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GhostState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pacman_2eproto_getter, &descriptor_table_pacman_2eproto_once,
      file_level_metadata_pacman_2eproto[0]);
}

// ===================================================================

class GameState::_Internal {
 public:
};

GameState::GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pacman.GameState)
}
GameState::GameState(const GameState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ghosts_){from._impl_.ghosts_}
    , decltype(_impl_.pebble_array_){from._impl_.pebble_array_}
    , /*decltype(_impl_._pebble_array_cached_byte_size_)*/{0}
    , decltype(_impl_.pac_x_){}
    , decltype(_impl_.pac_y_){}
    , decltype(_impl_.pac_angle_){}
    , decltype(_impl_.lives_){}
    , decltype(_impl_.points_){}
    , decltype(_impl_.animate_){}
    , decltype(_impl_.gameover_){}
    , decltype(_impl_.start_wait_){}
    , decltype(_impl_.pebbles_left_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.pac_x_, &from._impl_.pac_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.pebbles_left_) -
    reinterpret_cast<char*>(&_impl_.pac_x_)) + sizeof(_impl_.pebbles_left_));
  // @@protoc_insertion_point(copy_constructor:pacman.GameState)
}

inline void GameState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ghosts_){arena}
    , decltype(_impl_.pebble_array_){arena}
    , /*decltype(_impl_._pebble_array_cached_byte_size_)*/{0}
    , decltype(_impl_.pac_x_){0}
    , decltype(_impl_.pac_y_){0}
    , decltype(_impl_.pac_angle_){0}
    , decltype(_impl_.lives_){0}
    , decltype(_impl_.points_){0}
    , decltype(_impl_.animate_){false}
    , decltype(_impl_.gameover_){false}
    , decltype(_impl_.start_wait_){false}
    , decltype(_impl_.pebbles_left_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameState::~GameState() {
  // @@protoc_insertion_point(destructor:pacman.GameState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GameState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ghosts_.~RepeatedPtrField();
  _impl_.pebble_array_.~RepeatedField();
}

void GameState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameState::Clear() {
// @@protoc_insertion_point(message_clear_start:pacman.GameState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ghosts_.Clear();
  _impl_.pebble_array_.Clear();
  ::memset(&_impl_.pac_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.pebbles_left_) -
      reinterpret_cast<char*>(&_impl_.pac_x_)) + sizeof(_impl_.pebbles_left_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double pac_x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.pac_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double pac_y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.pac_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double pac_angle = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.pac_angle_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool animate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.animate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 lives = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.lives_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 points = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.points_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool gameover = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.gameover_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool start_wait = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.start_wait_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pebbles_left = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.pebbles_left_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .pacman.GhostState ghosts = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ghosts(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated int32 pebble_array = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_pebble_array(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 88) {
          _internal_add_pebble_array(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pacman.GameState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double pac_x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_x = this->_internal_pac_x();
  uint64_t raw_pac_x;
  memcpy(&raw_pac_x, &tmp_pac_x, sizeof(tmp_pac_x));
  if (raw_pac_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_pac_x(), target);
  }

  // double pac_y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_y = this->_internal_pac_y();
  uint64_t raw_pac_y;
  memcpy(&raw_pac_y, &tmp_pac_y, sizeof(tmp_pac_y));
  if (raw_pac_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_pac_y(), target);
  }

  // double pac_angle = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_angle = this->_internal_pac_angle();
  uint64_t raw_pac_angle;
  memcpy(&raw_pac_angle, &tmp_pac_angle, sizeof(tmp_pac_angle));
  if (raw_pac_angle != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_pac_angle(), target);
  }

  // bool animate = 4;
  if (this->_internal_animate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_animate(), target);
  }

  // int32 lives = 5;
  if (this->_internal_lives() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_lives(), target);
  }

  // int32 points = 6;
  if (this->_internal_points() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_points(), target);
  }

  // bool gameover = 7;
  if (this->_internal_gameover() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_gameover(), target);
  }

  // bool start_wait = 8;
  if (this->_internal_start_wait() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_start_wait(), target);
  }

  // int32 pebbles_left = 9;
  if (this->_internal_pebbles_left() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_pebbles_left(), target);
  }

  // repeated .pacman.GhostState ghosts = 10;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ghosts_size()); i < n; i++) {
    const auto& repfield = this->_internal_ghosts(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(10, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated int32 pebble_array = 11;
  {
    int byte_size = _impl_._pebble_array_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          11, _internal_pebble_array(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pacman.GameState)
  return target;
}

size_t GameState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pacman.GameState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pacman.GhostState ghosts = 10;
  total_size += 1UL * this->_internal_ghosts_size();
  for (const auto& msg : this->_impl_.ghosts_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated int32 pebble_array = 11;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.pebble_array_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._pebble_array_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // double pac_x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_x = this->_internal_pac_x();
  uint64_t raw_pac_x;
  memcpy(&raw_pac_x, &tmp_pac_x, sizeof(tmp_pac_x));
  if (raw_pac_x != 0) {
    total_size += 1 + 8;
  }

  // double pac_y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_y = this->_internal_pac_y();
  uint64_t raw_pac_y;
  memcpy(&raw_pac_y, &tmp_pac_y, sizeof(tmp_pac_y));
  if (raw_pac_y != 0) {
    total_size += 1 + 8;
  }

  // double pac_angle = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_angle = this->_internal_pac_angle();
  uint64_t raw_pac_angle;
  memcpy(&raw_pac_angle, &tmp_pac_angle, sizeof(tmp_pac_angle));
  if (raw_pac_angle != 0) {
    total_size += 1 + 8;
  }

  // int32 lives = 5;
  if (this->_internal_lives() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_lives());
  }

  // int32 points = 6;
  if (this->_internal_points() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_points());
  }

  // bool animate = 4;
  if (this->_internal_animate() != 0) {
    total_size += 1 + 1;
  }

  // bool gameover = 7;
  if (this->_internal_gameover() != 0) {
    total_size += 1 + 1;
  }

  // bool start_wait = 8;
  if (this->_internal_start_wait() != 0) {
    total_size += 1 + 1;
  }

  // int32 pebbles_left = 9;
  if (this->_internal_pebbles_left() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pebbles_left());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameState::GetClassData() const { return &_class_data_; }


void GameState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameState*>(&to_msg);
  auto& from = static_cast<const GameState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pacman.GameState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.ghosts_.MergeFrom(from._impl_.ghosts_);
  _this->_impl_.pebble_array_.MergeFrom(from._impl_.pebble_array_);
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_x = from._internal_pac_x();
  uint64_t raw_pac_x;
  memcpy(&raw_pac_x, &tmp_pac_x, sizeof(tmp_pac_x));
  if (raw_pac_x != 0) {
    _this->_internal_set_pac_x(from._internal_pac_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_y = from._internal_pac_y();
  uint64_t raw_pac_y;
  memcpy(&raw_pac_y, &tmp_pac_y, sizeof(tmp_pac_y));
  if (raw_pac_y != 0) {
    _this->_internal_set_pac_y(from._internal_pac_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pac_angle = from._internal_pac_angle();
  uint64_t raw_pac_angle;
  memcpy(&raw_pac_angle, &tmp_pac_angle, sizeof(tmp_pac_angle));
  if (raw_pac_angle != 0) {
    _this->_internal_set_pac_angle(from._internal_pac_angle());
  }
  if (from._internal_lives() != 0) {
    _this->_internal_set_lives(from._internal_lives());
  }
  if (from._internal_points() != 0) {
    _this->_internal_set_points(from._internal_points());
  }
  if (from._internal_animate() != 0) {
    _this->_internal_set_animate(from._internal_animate());
  }
  if (from._internal_gameover() != 0) {
    _this->_internal_set_gameover(from._internal_gameover());
  }
  if (from._internal_start_wait() != 0) {
    _this->_internal_set_start_wait(from._internal_start_wait());
  }
  if (from._internal_pebbles_left() != 0) {
    _this->_internal_set_pebbles_left(from._internal_pebbles_left());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameState::CopyFrom(const GameState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pacman.GameState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameState::IsInitialized() const {
  return true;
}

void GameState::InternalSwap(GameState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ghosts_.InternalSwap(&other->_impl_.ghosts_);
  _impl_.pebble_array_.InternalSwap(&other->_impl_.pebble_array_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameState, _impl_.pebbles_left_)
      + sizeof(GameState::_impl_.pebbles_left_)
      - PROTOBUF_FIELD_OFFSET(GameState, _impl_.pac_x_)>(
          reinterpret_cast<char*>(&_impl_.pac_x_),
          reinterpret_cast<char*>(&other->_impl_.pac_x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pacman_2eproto_getter, &descriptor_table_pacman_2eproto_once,
      file_level_metadata_pacman_2eproto[1]);
}

// ===================================================================

class KeyInput::_Internal {
 public:
};

KeyInput::KeyInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pacman.KeyInput)
}
KeyInput::KeyInput(const KeyInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KeyInput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.action_){}
    , decltype(_impl_.pressed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.action_, &from._impl_.action_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.pressed_) -
    reinterpret_cast<char*>(&_impl_.action_)) + sizeof(_impl_.pressed_));
  // @@protoc_insertion_point(copy_constructor:pacman.KeyInput)
}

inline void KeyInput::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.action_){0}
    , decltype(_impl_.pressed_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

KeyInput::~KeyInput() {
  // @@protoc_insertion_point(destructor:pacman.KeyInput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KeyInput::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void KeyInput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KeyInput::Clear() {
// @@protoc_insertion_point(message_clear_start:pacman.KeyInput)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.action_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.pressed_) -
      reinterpret_cast<char*>(&_impl_.action_)) + sizeof(_impl_.pressed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KeyInput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .pacman.KeyAction action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_action(static_cast<::pacman::KeyAction>(val));
        } else
          goto handle_unusual;
        continue;
      // bool pressed = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.pressed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KeyInput::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pacman.KeyInput)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .pacman.KeyAction action = 1;
  if (this->_internal_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_action(), target);
  }

  // bool pressed = 2;
  if (this->_internal_pressed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_pressed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pacman.KeyInput)
  return target;
}

size_t KeyInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pacman.KeyInput)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .pacman.KeyAction action = 1;
  if (this->_internal_action() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_action());
  }

  // bool pressed = 2;
  if (this->_internal_pressed() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KeyInput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KeyInput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KeyInput::GetClassData() const { return &_class_data_; }


void KeyInput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KeyInput*>(&to_msg);
  auto& from = static_cast<const KeyInput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pacman.KeyInput)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_action() != 0) {
    _this->_internal_set_action(from._internal_action());
  }
  if (from._internal_pressed() != 0) {
    _this->_internal_set_pressed(from._internal_pressed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KeyInput::CopyFrom(const KeyInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pacman.KeyInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyInput::IsInitialized() const {
  return true;
}

void KeyInput::InternalSwap(KeyInput* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyInput, _impl_.pressed_)
      + sizeof(KeyInput::_impl_.pressed_)
      - PROTOBUF_FIELD_OFFSET(KeyInput, _impl_.action_)>(
          reinterpret_cast<char*>(&_impl_.action_),
          reinterpret_cast<char*>(&other->_impl_.action_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KeyInput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pacman_2eproto_getter, &descriptor_table_pacman_2eproto_once,
      file_level_metadata_pacman_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pacman
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pacman::GhostState*
Arena::CreateMaybeMessage< ::pacman::GhostState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pacman::GhostState >(arena);
}
template<> PROTOBUF_NOINLINE ::pacman::GameState*
Arena::CreateMaybeMessage< ::pacman::GameState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pacman::GameState >(arena);
}
template<> PROTOBUF_NOINLINE ::pacman::KeyInput*
Arena::CreateMaybeMessage< ::pacman::KeyInput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pacman::KeyInput >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
